#define icon_action_add "\Nurmi_News_Outlet\data\icon_action_article_ac.paa"
#define icon_action_main "\Nurmi_News_Outlet\data\icon_action_main_ca.paa"
#define icon_module_main "\Nurmi_News_Outlet\data\icon_module_main_ca.paa"
#define icon_module_image "\Nurmi_News_Outlet\data\icon_module_image_ca.paa"
#define icon_module_bio "\Nurmi_News_Outlet\data\icon_module_bio_ca.paa"